let dataStorage = [
  {
    courseId: "cv001",
    courseName: "Java",
    courseDuration: "2",
    status: "Active",
    arrClass: [
      {
        classId: "cl001",
        className: "HN-JV001",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st001",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st002",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st003",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st004",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st005",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st006",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st007",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
      {
        classId: "cl002",
        className: "HN-JV002",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st008",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st009",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st010",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st011",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st012",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st013",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st014",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
    ],
  },
  {
    courseId: "cv002",
    courseName: "ReactJs",
    courseDuration: "3",
    status: "Active",
    arrClass: [
      {
        classId: "cl003",
        className: "HN-React001",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st015",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st016",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st017",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st018",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st019",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st020",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st021",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
      {
        classId: "cl004",
        className: "HN-React002",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st022",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st023",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st024",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st025",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st026",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st027",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st028",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
    ],
  },
  {
    courseId: "cv003",
    courseName: "Python",
    courseDuration: "5",
    status: "Active",
    arrClass: [
      {
        classId: "cl005",
        className: "HN-Python001",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st029",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st030",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st031",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st032",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st033",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st034",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st035",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
      {
        classId: "cl006",
        className: "HN-Python002",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st036",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st037",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st038",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st039",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st040",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st041",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st042",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
    ],
  },
  {
    courseId: "cv004",
    courseName: "C#",
    courseDuration: "6",
    status: "Active",
    arrClass: [
      {
        classId: "cl007",
        className: "HN-C#001",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st043",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st044",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st045",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st046",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st047",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st048",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st049",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
      {
        classId: "cl008",
        className: "HN-C#002",
        lecturer: "Peter Parker",
        description: "fullstack",
        numberOfStudent: "7",
        status: "Active",
        studentArr: [
          {
            studentId: "st050",
            fullName: "Philip Lahm",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st051",
            fullName: "Bastian Schweinsteiger",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st052",
            fullName: "Miroslav Klose",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st053",
            fullName: "Lukas Podolski",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st054",
            fullName: "Mesut Özil",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st055",
            fullName: "Oliver Kahn",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
          {
            studentId: "st056",
            fullName: "Jérôme Boateng",
            yearOfBirth: "1994",
            address: "Thai Binh",
            status: "Active",
          },
        ],
      },
    ],
  },
];
let userSystem = [
  { userId: 1, email: "peter@gmail.com", password: "123456" },
  { userId: 2, email: "peterParker@gmail.com", password: "123456" },
];
// localStorage.setItem("Data Management", JSON.stringify(dataStorage));
// localStorage.setItem("User Data", JSON.stringify(userSystem));
